# This file serves as a template for the configuration file. Copy it and edit the values as needed.
# Use --config parameter to specify the path to the configuration file.


[logger]
level = "INFO"
file = "./logs/flare-tlc.log"
console = true

[metrics]
# used for prometheus metrics of the client
# currently, no specific data are included in the metrics in addition to the default ones
prometheus_address = "localhost:2112"

[chain]
node_url = "http://127.0.0.1:8545"
address_hrp = "localflare"
chain_id = 162
# eth_rpc_url is needed for services
eth_rpc_url = "http://127.0.0.1:8545"
# api key may be needed for access to production nodes
api_key = ""
# private_key_file is needed for voting and mirroring clients
private_key_file = "./privateKey"

[contract_addresses]
submission = "0x6082731fdAba4761277Fb31299ebC782AD3bCf24"
system_manager = "0x5A0773Ff307Bf7C71a832dBB5312237fD3437f9F"

[ftso_v2]